/**
 * Textos de las cotizaciones (fase F11). Contenido desacoplado de los
 * componentes (ADR-05).
 */
export const COTIZACIONES = {
  panel: {
    titulo: 'Cotizaciones',
    intro: 'Arma, envía y sigue las cotizaciones del pipeline comercial.',
    nueva: 'Nueva cotización',
    filtroTodas: 'Todas',
    sinResultados: 'Todavía no hay cotizaciones con ese estado.',
    columnaNumero: 'Número',
    columnaCliente: 'Cliente',
    columnaTotal: 'Total',
    columnaEstado: 'Estado',
    columnaValidez: 'Válida hasta',
    cargando: 'Cargando cotizaciones…',
    error: 'No pudimos cargar las cotizaciones. Intenta de nuevo.',
  },
  detalle: {
    volver: 'Volver a cotizaciones',
    tituloBorrador: 'Borrador de cotización',
    itemsTitulo: 'Ítems',
    agregarItem: 'Agregar ítem',
    quitarItem: 'Quitar',
    labelDescripcion: 'Descripción',
    labelCantidad: 'Cantidad',
    labelValorUnitario: 'Valor unitario',
    labelNotas: 'Notas para el cliente',
    labelCliente: 'Cliente',
    labelCorreo: 'Correo del cliente',
    labelTelefono: 'Teléfono (opcional)',
    labelIdentificacion: 'NIT o cédula (opcional)',
    labelImpuesto: 'Impuesto (%)',
    labelValidez: 'Días de validez',
    guardar: 'Guardar borrador',
    guardando: 'Guardando…',
    enviar: 'Enviar al cliente',
    enviando: 'Enviando…',
    descargar: 'Descargar PDF',
    cancelar: 'Cancelar cotización',
    confirmarCancelar: '¿Seguro que quieres cancelar esta cotización? No se puede deshacer.',
    confirmarEnviar:
      'Al enviarla recibe su número y ya no se puede editar. ¿La enviamos al cliente?',
    subtotal: 'Subtotal',
    impuesto: 'Impuesto',
    total: 'Total',
    avisoCongelada: 'Esta cotización ya fue enviada: sus ítems no se pueden modificar.',
    errorGuardar: 'No pudimos guardar el borrador.',
    errorEnviar: 'No pudimos enviarla. Revisa que tenga al menos un ítem.',
    sinItems: 'Agrega al menos un ítem para poder enviarla.',
  },
  cliente: {
    titulo: 'Mis cotizaciones',
    intro: 'Aquí llegan las cotizaciones que te enviamos. Puedes descargarlas y responderlas.',
    vacio: 'Todavía no tienes cotizaciones. Cuando te enviemos una, aparecerá aquí.',
    cargando: 'Cargando tus cotizaciones…',
    error: 'No pudimos cargar tus cotizaciones. Intenta de nuevo.',
    verDetalle: 'Ver detalle',
    volver: 'Volver a mis cotizaciones',
    descargar: 'Descargar PDF',
    aceptar: 'Aceptar cotización',
    rechazar: 'Rechazar',
    confirmarAceptar: 'Al aceptar, nos pondremos en contacto para arrancar. ¿Confirmas?',
    confirmarRechazar: '¿Confirmas que rechazas esta cotización?',
    respondida: 'Ya respondiste esta cotización.',
    vencida: 'Esta cotización venció. Escríbenos y te preparamos una nueva.',
    validaHasta: 'Válida hasta',
    errorResponder: 'No pudimos registrar tu respuesta. Intenta de nuevo.',
  },
  estados: {
    BORRADOR: 'Borrador',
    ENVIADA: 'Enviada',
    ACEPTADA: 'Aceptada',
    RECHAZADA: 'Rechazada',
    VENCIDA: 'Vencida',
    CANCELADA: 'Cancelada',
  } as Record<string, string>,
} as const;
