import type { EstadoEntregable, EstadoProyecto, MedioDePago } from '../app/api/proyectos-api';

/**
 * Textos del portal de proyectos del cliente (F12, HU-49 a HU-57).
 * Lenguaje del cliente, no técnico: nada de "sprint" ni "deploy".
 */
export const PROYECTOS = {
  cuenta: {
    titulo: 'Mi proyecto',
    tituloVarios: 'Mis proyectos',
    verProyecto: 'Ver mi proyecto',
    avance: 'Avance',
    paraRevisarUno: 'Tienes 1 entrega para revisar',
    paraRevisarVarios: 'Tienes {n} entregas para revisar',
    pagoPendiente: 'Pago pendiente:',
    error: 'No pudimos cargar tus proyectos. Recarga la página en un momento.',
  },
  detalle: {
    volver: 'Volver a mi cuenta',
    cargando: 'Cargando tu proyecto…',
    error: 'No pudimos cargar tu proyecto. Revisa tu conexión e inténtalo de nuevo.',
    reintentar: 'Reintentar',
    noEncontrado: 'No encontramos este proyecto en tu cuenta.',
    inicio: 'Inicio',
    entregaEstimada: 'Entrega estimada',
    garantiaHasta: 'Garantía hasta el',
    avance: 'Avance del proyecto',
    avanceExplicacion: 'Se mide por el valor de lo que ya aprobaste.',
    paraRevisarTitulo: 'Listo para que lo mires',
    paraRevisarIntro: 'Estas entregas esperan tu revisión. Apruébalas o dinos qué ajustar.',
    planTitulo: 'El plan, fase por fase',
    planVacio: 'Estamos armando tu plan. Apenas esté, lo verás aquí con sus fases y entregas.',
    lasFechas: 'Del {inicio} al {fin}',
    resumenDeFase: 'Lo que se hizo',
    cambioDeAlcance: 'Agregado al proyecto',
    verDemo: 'Ver demo',
    abreEnPestanaNueva: '(se abre en una pestaña nueva)',
    queSeAjusta: 'Qué se está ajustando:',
    aprobar: 'Aprobar',
    pedirAjustes: 'Pedir ajustes',
    confirmarAprobacion: '¿Apruebas «{nombre}»? Si se cobra al aprobarse, quedará como pago pendiente.',
    siAprobar: 'Sí, aprobar',
    cancelar: 'Cancelar',
    labelAjustes: '¿Qué hay que ajustar?',
    ayudaAjustes: 'Cuéntanos con tus palabras qué cambiarías. Lo leemos y te avisamos cuando esté.',
    enviarAjustes: 'Enviar ajustes',
    errorAjustesVacio: 'Escribe qué hay que ajustar.',
    errorAlResponder: 'No pudimos guardar tu respuesta. Inténtalo de nuevo.',
    aprobadoPorTi: 'Lo aprobaste el {fecha}',
    aprobadoPorEquipo: 'Aprobado el {fecha}',
    pagosTitulo: 'Tus pagos',
    pagosIntro: 'Cada entrega se paga según lo acordado: la primera al iniciar y las demás al aprobarlas.',
    totalDelProyecto: 'Total del proyecto',
    totalPagado: 'Pagado',
    saldo: 'Saldo',
    pendienteAhora: 'Por pagar ahora',
    valor: 'Total con IVA',
    impuesto: 'IVA incluido',
    pagado: 'Pagado',
    pendiente: 'Por pagar',
    todaviaNo: 'Se cobra al aprobarse',
    pagadoCompleto: 'Al día',
    sinPagos: 'Todavía no hay pagos registrados.',
    historialTitulo: 'Pagos registrados',
    noEsFactura: 'Este resumen es informativo: no es una factura.',
  },
  estadosDelEntregable: {
    PENDIENTE: 'Pendiente',
    EN_CURSO: 'En construcción',
    EN_REVISION: 'Para revisar',
    CON_AJUSTES: 'Con ajustes',
    APROBADO: 'Aprobado',
  } satisfies Record<EstadoEntregable, string>,
  estadosDelProyecto: {
    ACTIVO: 'En marcha',
    PAUSADO: 'En pausa',
    EN_GARANTIA: 'En garantía',
    CERRADO: 'Cerrado',
  } satisfies Record<EstadoProyecto, string>,
  mediosDePago: {
    TRANSFERENCIA: 'Transferencia',
    NEQUI_DAVIPLATA: 'Nequi / Daviplata',
    EFECTIVO: 'Efectivo',
    LINK_DE_PAGO: 'Link de pago',
  } satisfies Record<MedioDePago, string>,
} as const;
