import type { EstadoEntregable, EstadoProyecto, MedioDePago } from '../app/api/proyectos-api';

/**
 * Textos del portal de proyectos del cliente (F12, HU-49 a HU-57).
 * Lenguaje del cliente, no técnico: nada de "sprint" ni "deploy".
 */
export const PROYECTOS = {
  cuenta: {
    titulo: 'Mi proyecto',
    tituloVarios: 'Mis proyectos',
    verProyecto: 'Ver mi proyecto',
    avance: 'Avance',
    paraRevisarUno: 'Tienes 1 entrega para revisar',
    paraRevisarVarios: 'Tienes {n} entregas para revisar',
    pagoPendiente: 'Pago pendiente:',
    error: 'No pudimos cargar tus proyectos. Recarga la página en un momento.',
  },
  detalle: {
    volver: 'Volver a mi cuenta',
    cargando: 'Cargando tu proyecto…',
    error: 'No pudimos cargar tu proyecto. Revisa tu conexión e inténtalo de nuevo.',
    reintentar: 'Reintentar',
    noEncontrado: 'No encontramos este proyecto en tu cuenta.',
    inicio: 'Inicio',
    entregaEstimada: 'Entrega estimada',
    garantiaHasta: 'Garantía hasta el',
    avance: 'Avance del proyecto',
    avanceExplicacion: 'Se mide por el valor de lo que ya aprobaste.',
    paraRevisarTitulo: 'Listo para que lo mires',
    paraRevisarIntro: 'Estas entregas esperan tu revisión. Apruébalas o dinos qué ajustar.',
    planTitulo: 'El plan, fase por fase',
    planVacio: 'Estamos armando tu plan. Apenas esté, lo verás aquí con sus fases y entregas.',
    lasFechas: 'Del {inicio} al {fin}',
    resumenDeFase: 'Lo que se hizo',
    cambioDeAlcance: 'Agregado al proyecto',
    verDemo: 'Ver demo',
    abreEnPestanaNueva: '(se abre en una pestaña nueva)',
    queSeAjusta: 'Qué se está ajustando:',
    aprobar: 'Aprobar',
    pedirAjustes: 'Pedir ajustes',
    confirmarAprobacion: '¿Apruebas «{nombre}»? Si se cobra al aprobarse, quedará como pago pendiente.',
    siAprobar: 'Sí, aprobar',
    cancelar: 'Cancelar',
    labelAjustes: '¿Qué hay que ajustar?',
    ayudaAjustes: 'Cuéntanos con tus palabras qué cambiarías. Lo leemos y te avisamos cuando esté.',
    enviarAjustes: 'Enviar ajustes',
    errorAjustesVacio: 'Escribe qué hay que ajustar.',
    errorAlResponder: 'No pudimos guardar tu respuesta. Inténtalo de nuevo.',
    aprobadoPorTi: 'Lo aprobaste el {fecha}',
    aprobadoPorEquipo: 'Aprobado el {fecha}',
    pagosTitulo: 'Tus pagos',
    pagosIntro: 'Cada entrega se paga según lo acordado: la primera al iniciar y las demás al aprobarlas.',
    totalDelProyecto: 'Total del proyecto',
    totalPagado: 'Pagado',
    saldo: 'Saldo',
    pendienteAhora: 'Por pagar ahora',
    valor: 'Total con IVA',
    impuesto: 'IVA incluido',
    pagado: 'Pagado',
    pendiente: 'Por pagar',
    todaviaNo: 'Se cobra al aprobarse',
    pagadoCompleto: 'Al día',
    sinPagos: 'Todavía no hay pagos registrados.',
    historialTitulo: 'Pagos registrados',
    noEsFactura: 'Este resumen es informativo: no es una factura.',
  },
  panel: {
    navProyectos: 'Proyectos',
    listadoTitulo: 'Proyectos',
    listadoIntro: 'Lo que el cliente ve en su cuenta. Cada proyecto nace de una cotización aceptada o en blanco.',
    nuevoEnBlanco: 'Proyecto en blanco',
    cargando: 'Cargando…',
    error: 'No se pudo cargar. Revisa la conexión y recarga.',
    vacio: 'Todavía no hay proyectos. Créalo desde una cotización aceptada o en blanco.',
    columnaProyecto: 'Proyecto',
    columnaCliente: 'Cliente',
    columnaEstado: 'Estado',
    columnaAvance: 'Avance',
    columnaPorCobrar: 'Por cobrar ahora',
    columnaSaldo: 'Saldo',
    volverAlListado: 'Proyectos',
    // Desde la cotización
    crearDesdeCotizacion: 'Crear proyecto',
    verProyectoDeCotizacion: 'Ver su proyecto',
    // Nuevo
    nuevoTitulo: 'Nuevo proyecto',
    nuevoDesdeCotizacion: 'Desde la cotización {numero}, aceptada por {cliente}.',
    nuevoIntroBlanco: 'Un proyecto sin cotización: escribe los datos del cliente y arma el plan.',
    seccionCliente: 'Cliente',
    labelClienteNombre: 'Nombre o empresa',
    labelClienteCorreo: 'Correo del cliente',
    ayudaClienteCorreo: 'Es el correo con el que el cliente entra a su cuenta. Si todavía no tiene cuenta, verá el proyecto cuando se registre con él.',
    labelImpuesto: 'IVA (%)',
    seccionDescripcion: 'El proyecto',
    labelNombre: 'Nombre del proyecto',
    labelDescripcion: 'Descripción para el cliente',
    labelInicio: 'Inicio',
    labelEntregaEstimada: 'Entrega estimada',
    seccionPlan: 'El plan',
    ayudaPlan: 'Las entregas salen de los ítems de la cotización. Puedes reagruparlas en fases y renombrarlas, pero tienen que sumar lo que el cliente aceptó.',
    labelFase: 'Nombre de la fase',
    labelObjetivo: 'Objetivo (1-2 frases para el cliente)',
    labelEntregable: 'Entrega',
    labelValor: 'Valor sin IVA',
    labelCobro: 'Se cobra',
    cobroAlIniciar: 'Al iniciar (anticipo)',
    cobroAlAprobar: 'Al aprobarse',
    agregarFase: 'Agregar fase',
    quitarFase: 'Quitar fase',
    agregarEntregable: 'Agregar entrega',
    quitarEntregable: 'Quitar',
    sumaDelPlan: 'Suma del plan',
    sumaAceptada: 'Aceptado en la cotización',
    diferencia: 'Diferencia',
    crear: 'Crear proyecto',
    creando: 'Creando…',
    // Detalle
    sinCuenta: 'Este correo todavía no tiene cuenta: el cliente verá el proyecto cuando se registre con él.',
    editar: 'Editar',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    subir: 'Subir',
    bajar: 'Bajar',
    moverA: 'Mover a',
    resumenDeFase: 'Resumen para el cliente al cerrar la fase',
    guardarResumen: 'Guardar resumen',
    cambioDeAlcance: 'Cambio de alcance',
    esCambioDeAlcance: 'Es un cambio de alcance (algo que no estaba en lo aceptado)',
    cambioDeAlcanceObligatorio: 'En este proyecto todo lo nuevo entra como cambio de alcance.',
    enlaceDemo: 'Enlace de la demo (https://…)',
    guardarDemo: 'Guardar enlace',
    notaDeAjustes: 'Qué hay que ajustar',
    estadoActual: 'Estado',
    pagosTitulo: 'Pagos',
    registrarPago: 'Registrar pago',
    labelEntregaDelPago: 'Entrega',
    labelMonto: 'Monto recibido',
    labelFechaPago: 'Fecha',
    labelMedio: 'Medio',
    labelReferencia: 'Referencia o nota (opcional)',
    sinPagos: 'Todavía no hay pagos.',
    pausar: 'Pausar proyecto',
    reanudar: 'Reanudar proyecto',
    cerrar: 'Cerrar proyecto',
    confirmarPausa: '¿Pausar el proyecto? Mientras esté en pausa, las entregas no cambian de estado.',
    confirmarCierre: '¿Cerrar el proyecto antes de que venza la garantía? No se puede deshacer.',
    confirmar: 'Sí, continuar',
    garantiaHasta: 'En garantía hasta el',
    retomar: 'Retomar',
    tituloNuevaFase: 'Agregar una fase',
    tituloNuevaEntrega: 'Agregar una entrega',
  },
  accionesDelEquipo: {
    EN_CURSO: 'Empezar',
    EN_REVISION: 'Enviar a revisión',
    APROBADO: 'Marcar aprobado',
    CON_AJUSTES: 'Devolver con ajustes',
    PENDIENTE: '',
  } satisfies Record<EstadoEntregable, string>,
  estadosDelEntregable: {
    PENDIENTE: 'Pendiente',
    EN_CURSO: 'En construcción',
    EN_REVISION: 'Para revisar',
    CON_AJUSTES: 'Con ajustes',
    APROBADO: 'Aprobado',
  } satisfies Record<EstadoEntregable, string>,
  estadosDelProyecto: {
    ACTIVO: 'En marcha',
    PAUSADO: 'En pausa',
    EN_GARANTIA: 'En garantía',
    CERRADO: 'Cerrado',
  } satisfies Record<EstadoProyecto, string>,
  mediosDePago: {
    TRANSFERENCIA: 'Transferencia',
    NEQUI_DAVIPLATA: 'Nequi / Daviplata',
    EFECTIVO: 'Efectivo',
    LINK_DE_PAGO: 'Link de pago',
  } satisfies Record<MedioDePago, string>,
} as const;
