spring.application.name=leads

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:leads}
spring.datasource.username=${DB_USER:leads}
spring.datasource.password=${DB_PASSWORD:leads}

management.endpoint.health.show-details=when-authorized

